name: built_value_bug
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  built_value: ^8.4.4
